language: python
sudo: False
python:
- 3.4
- 3.5
- 3.6
- pypy
- nightly # 3.6

install:
- pip install -r requirements.txt
- pip install -r requirements_dev.txt

script: make travis

after_success:
- coveralls
